### ISSUE TITLE
想问下iteration是为了什么

### ISSUE THREAD

**Issue by SefaZeng** [Rayarrow/New-Word-Discovery#3]
不应该是统计完各个词的互信息和左右熵之后就可以排序得到新词了吗，为什么要迭代几次？代码没太看懂

**Comment by Rayarrow** [comment]
因为方法实现上是基于预切词的，举个例子：
假如第一轮迭代切出来个：吃/好/日/骚，那么第一轮结束可以得到"吃好"和"日骚"两个词，然后这两个词添加进词库进行第二轮迭代，得到：
吃好/日骚，第二轮结束就可以得到词：“吃好日骚”
如果不迭代的话，那就要设定一个长度不定的窗口，来计算“吃”、“好”、“日”、“骚”这四个词的共现统计信息，效率比较低而且麻烦了点

更极端的说，这种预切词迭代的方法即使你没有词库，只要语料足够大，多轮迭代之后可以早出来个词库，只是第一轮切词的时候按每个字来切

**Comment by SefaZeng** [comment]
就是每轮得到新词之后再加入jieba字典 然后再切词是吧
不过第一轮也是用jieba切词吧 只不过没有特殊的词典 为什么说是按每个字来切？

**Comment by Rayarrow** [comment]
对的
我选择的预切词词典就是jieba的默认配置的词典，我说的第一轮按每个字切呢，是说如果你把jieba的词典给清空了的话，那样基本就是按每个字来切了。想说明的就是这种迭代式新词发现方法的好处

**Comment by SefaZeng** [comment]
多谢！

**Comment by muzier** [comment]
那是不是多迭代几轮，可以得到更长的新词呢？如果确实新词本身较长（比如10个字），而且边界熵都比较大，通过增加迭代轮数是不是可以发现更长的新词？

**Comment by Rayarrow** [comment]
是的，但是召回不太好保证，需要自己手动调整一下阈值。
