### ISSUE TITLE
请教：还可以发现更长的新词吗？

### ISSUE THREAD

**Issue by muzier** [Rayarrow/New-Word-Discovery#5]
你好，请教一下：还可以发现更长的新词吗？是否可以通过变更参数来实现呢？谢谢

**Comment by Rayarrow** [comment]
可以，增加迭代数可以发现更长的词，但是召回率比较差。如果想保证精度，就把阈值设置低一些，然后自己手动筛选一下。比较好的方式应该是增加4个unigram甚至5个unigram组成的词，但是考虑性能问题，当时并没有增加这个。

**Comment by muzier** [comment]
明白了，非常感谢！
